name: Update Cargo.lock

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: personal

      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0

      - name: Run cargo update
        run: cargo update

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: "chore: update Cargo.lock [skip ci]"
          file_pattern: Cargo.lock
